### ISSUE TITLE
To determine the criteria for prioritizing the selection of a specific ontology term

### ISSUE THREAD

**Issue by lexmapr** [Public-Health-Bioinformatics/LexMapr#38]
The issue is to determine the criteria for prioritizing a specific ontology term compared to other ontologies for mapping given the case of multiple ontologies selected or term coming from multiple sources in a single ontology.
Possible options could be:
•	Asking from user about priority when he is selecting ontologies as input, 
•	or the domain and type of input data 
•	or rules that emerge when we analyze the ambiguous matches.

**Comment by ivansg44** [comment]
When an ontology is fetched, it will overwrite any conflicting terms that were inserted into the lookup table from previously fetched ontologies. Therefore, another option for prioritising online ontology mapping is to control the order ontologies are fetched.

Ontologies are currently fetched in a random order, after their IRI values are loaded from a JSON config file into a `dict` for iteration. [We could instead load the IRI values into an `OrderedDict`, that preserves the order seen in the config file.](https://stackoverflow.com/questions/6921699/can-i-get-json-to-load-into-an-ordereddict/6921760#6921760) Thus, the user would be able to prioritise specific ontologies by listing them further down within their config file.

If prioritising ontologies that are listed further down is non-intuitive, we could iterate through the `OrderedDict` backwards, and prioritize ontologies listed higher up within their config file instead.
