### ISSUE TITLE
More explanations/Manual

### ISSUE THREAD

**Issue by ajkarloss** [Public-Health-Bioinformatics/LexMapr#55]
Hi, We want to explore the tool to see if we can use it. Could you help me to find documentation or something to know more?

**Comment by ivansg44** [comment]
Thank you for your patience. As we have continued to develop LexMapr, we have also continued to improve our documentation. We now have ample documentation for users:

- [Formal documentation](https://genepio.org/lexmapr-documentation/)
- [Tutorial slides](https://github.com/Public-Health-Bioinformatics/LexMapr/blob/master/docs/tutorial_slides.pdf)

We also have a GUI, that currently focuses primarily on food and environment samples:

- [GUI](https://watson.bccdc.med.ubc.ca/lexmapr/)
- [GUI user guide](https://watson.bccdc.med.ubc.ca/lexmapr/user-guide/)
