### ISSUE TITLE
Refactor LexMapr\lexmapr\pipeline.py

### ISSUE THREAD

**Issue by ivansg44** [Public-Health-Bioinformatics/LexMapr#9]
LexMapr\lexmapr\pipeline.py should be more abstracted, and adhere to PEP style guidelines.

**Comment by Public-Health-Bioinformatics** [comment]
One thought about preProcess(): the work it takes to determine if a substring is in stringToken is probably the same amount as required in the search and replace pass, so the code can be simplified if no transform log needed:
```
# 4-Method to simply pre-process the string token on some pre-determined parts [\ , . ]
def preProcess(stringToken):
    if ('\'s' in stringToken):
        stringToken1 = stringToken.replace("\'s", "")  # for cow's to cow
        stringToken = stringToken1
    if (',' in stringToken):  # comma concatenated in token is get rid of
        stringToken1 = stringToken.rstrip(', ')
        stringToken = stringToken1
    if ('.' in stringToken):  # dot concatenated in token is get rid of
        stringToken1 = stringToken.rstrip('. ')
        stringToken = stringToken1
    return stringToken
```
can become
def preProcess(stringToken):
    # drop possessives
        stringToken = stringToken.replace("\'s", "") 
    # drop rightmost comma
        stringToken = stringToken.rstrip(', ')
    # drop rightmost period
        stringToken = stringToken.rstrip('. ')
    return stringToken

Or even
def preProcess(stringToken):
    # Drop possessives, rightmost comma, period
    return stringToken.replace("\'s", "").rstrip(', ').rstrip('. ')
